#!/usr/bin/python3
"""find these two primes p and q of given n, n = p x q"""
import sys
from math import ceil, sqrt

with open(sys.argv[1], "r") as fp:
    n = int(fp.readline())
    # check if value is even
    if n % 2 == 0:
        print("{}={}*{}".format(n, int(n / 2), 2))
    # value is odd number
    else:
        a = int(ceil(sqrt(n)))
        while (True):
            b1 = a * a - n
            b = int(sqrt(b1))
            if(b * b == b1):
                break
            else:
                a += 1
        print("{}={}*{}".format(n, a + b, a - b))
